<?php
function custom_form_menu() {
  $items = array();

  $items['apigee/custom_form'] = array( 
    'title' => 'Custom Form', //page title
    'description' => 'A modular custom form.',
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('custom_form_form'), 
    'access callback' => TRUE
  );

   $items['admin/content/mymodule'] = array(
    'title' => t('My Form data'),
	'description' => t('My form data from custom form'),
    'page callback' => 'my_module_data',
    'access callback' => 'user_access',
	'access arguments' => array('access content'),
  );
  return $items;
}

function my_module_data() {

$result = db_query('SELECT * FROM {custom_form_one}');
  $records = $result->fetchAll();
  $content = '<pre>' . print_r($records, TRUE) . '</pre>';
  return $content;
}

function custom_form_form($form, &$form_state) {
  
  $form['first'] = array(
    '#type' => 'textfield',
    '#title' => t('First Name'),
	  '#required' => TRUE, // Added
	  '#size' => 20, // added
    '#maxlength' => 20, // added
  );
  $form['last'] = array(
    '#type' => 'textfield',
    '#title' => t('Last Name'),
	'#required' => TRUE, // Added
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
	'#required' => TRUE, // Added
  );
  $form['pass'] = array(
    '#type' => 'password',
    '#title' => t('Password'),
	'#required' => TRUE, // Added
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('submit'),
  );  
  return $form;
}

function custom_form_form_validate($form, &$form_state) {  
}

function custom_form_form_submit($form, &$form_state) {
    $nid = db_insert('custom_form_one')
  ->fields(array(
    'first' =>  $form_state['values']['first'], 
    'last' =>  $form_state['values']['last'],
    'email' =>  $form_state['values']['email'],
    'pass' =>  $form_state['values']['pass'],
  ))
  ->execute();

    drupal_set_message(t('The form has been submitted.'));
    $form_state['redirect'] = 'thank-you-page';
	}
?>
